name: CI Build Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-x86-64:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      - name: Check system
        run: cd repo_workspace && uname -a
