name: CI Build Check

on:
  push:
    branches: ["main", "master", "llm"]
  pull_request:
    branches: ["main", "master", "llm"]

jobs:
  linux-x86-64:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      - name: Install deps
        run: cd repo_workspace && bash .gitcode/scripts/euleros-install-deps.sh --linux-gui
      - name: Build
        run: cd repo_workspace && bash -c 'source .gitcode/.env && bash .gitcode/scripts/build-target.sh --build-target "$BUILD_TARGET_X86_64" --dist-targets "$DIST_TARGETS_X86_64"'

  linux-aarch64:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      - name: Install deps
        run: cd repo_workspace && bash .gitcode/scripts/euleros-install-deps.sh --linux-gui
      - name: Build
        run: cd repo_workspace && bash -c 'source .gitcode/.env && bash .gitcode/scripts/build-target.sh --build-target "$BUILD_TARGET_AARCH64" --dist-targets "$DIST_TARGETS_AARCH64"'

  windows-gnu:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      - name: Install deps
        run: cd repo_workspace && bash .gitcode/scripts/euleros-install-deps.sh --windows-cross
      - name: Build
        run: cd repo_workspace && bash -c 'source .gitcode/.env && bash .gitcode/scripts/build-target.sh --build-target "$BUILD_TARGET_WINDOWS" --dist-targets "$DIST_TARGETS_WINDOWS"'
