name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  release-job:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      - name: Check system
        run: cd repo_workspace && uname -a
