name: Release

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags:
      - v*.*.*

jobs:
  release-job:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      - name: Check system
        run: cd repo_workspace && uname -a
      - name: Check env
        run: cd repo_workspace && echo hello
